### ISSUE TITLE
Scala 2.11 Support

### ISSUE THREAD

**Issue by kevinherron** [t-pleasure/mighty-csv#3]
Any chance you can build and publish a 2.11 artifact to Maven?

**Comment by t-pleasure** [comment]
Hi Kevin, I need to see if I still have the credentials to push new artifacts (it might be associated with accounts from my previous job). If not, I'll ask whoever has the credentials to publish 2.11 artifacts. I'm on vacation right now, but will check up on it next week. I'll keep you posted, but feel free to ping me if you don't hear back from my by next weds. thank you.

**Comment by t-pleasure** [comment]
Just a quick update on this -- I've pushed the 2.11 artifacts to sonatype and am waiting for it to sync with the central maven repository. I'll keep you updated on this. Thank you.

**Comment by t-pleasure** [comment]
Hi Kevin, the 2.11 artifacts are now available on the Maven central repository. You can retrieve them with the following configs:

libraryDependencies += "com.bizo" % "mighty-csv_2.11" % "0.2"

Apologies for the delay and thanks for reaching out to me regarding this issue.

**Comment by kevinherron** [comment]
Thanks!
