### ISSUE TITLE
Header Transformation for upper/lower case

### ISSUE THREAD

**Issue by paul-christmann** [t-pleasure/mighty-csv#5]
I have a use case where I have to parse a CSV from a 3rd party which (unfortunately) may or may not contain capitalized headers when our systems expect lowercase headers.

I'd like to submit a PR that would allow for optionally injecting behavior to CSVDictReader to transform the headers during the load process so that they end up as lower case headers.  The other option (doing it in our systems) could be done, but I'd prefer to do it as CSV load time so the rest of the system can function identically under the previously defined "contract".

If I submit a PR for this, would you consider it?

**Comment by t-pleasure** [comment]
@paul-christmann thanks for reaching out. I feel your pain (I used to do a lot of data munging/cleaning of data from 3rd party data vendors), but I don't feel that it would be wise to add extra complexity to the code for a unique scenario such as this. One possibility would be to modify the headers immediately after you read them in. For example:

val reader = CSVReader("filename").map(case(row) => row.map{case(k,v) => (k.toLowerCase, v)})

This should allow you to access the headers in their lowercase form (just don't use the reader's header member). I hope this helps.

thank you,
-Tony

**Comment by paul-christmann** [comment]
Thanks for the feedback and that idea.  I'll look into that.  I'd prefer to use CSVDictReader, but I'll see what I can do with it.

Thanks
